#!/usr/bin/python3
"""Generate the Dockerfile that bakes the 2026-09-23 host production profile into one image.

Inputs are the MANIFEST-pinned files in profiles/production-dense-recovery-20260923/.
Build context is that profile directory. Run: python3 -I image/prod-dense-20260923/gen_dockerfile.py
"""
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
PROFILE = HERE.parents[1] / 'profiles/production-dense-recovery-20260923'
BASE = 'localhost/frank/vllm-nvfp4-kv-sm120:stability-core-v1-immutable'
BASE_ID = 'sha256:b6190f100526423e5855c5c0f98773744c91a69a7e112993d66bed038c9b76c6'
BASE_OVERLAY_MANIFEST_SHA256 = '57e211ef0ef41dad91d32c6c05b499dc5d803d25f7c9e617697036f7c7db8fee'


def load(name):
    return json.loads((PROFILE / name).read_text())


def main():
    env = load('environment.json')
    argv = load('graph-prefix.json')['argv']
    profiles = load('PROFILES.json')
    assert profiles['image'] == BASE_ID
    assert profiles['profiles']['graph-prefix']['argv'] == argv
    manifest_sha = json.loads((PROFILE.parents[1] / 'ACTIVE_PROFILE.json').read_text())['manifest_sha256']
    lines = [
        '# syntax=docker/dockerfile:1.7',
        '# GENERATED by gen_dockerfile.py; do not edit by hand.',
        f'# Base image ID must be {BASE_ID} (host-built; parent chain in its labels).',
        f'FROM {BASE}',
        'USER root',
        'COPY overlay/ /opt/qwen38-prod/overlay/',
        'COPY inspection/ /opt/qwen38-prod/inspection/',
        'COPY entry.py overlay-integrity.json inspection-integrity.json /candidate/',
        'COPY environment.json graph-prefix.json PROFILES.json MANIFEST.json /opt/qwen38-prod/',
        'RUN /usr/bin/python3 -I - <<\'PY\'',
        'import hashlib, json, os, shutil',
        'from pathlib import Path',
        'base = Path("/opt/frank-runtime-stability-image/overlay-manifest.json").read_bytes()',
        f'assert hashlib.sha256(base).hexdigest() == "{BASE_OVERLAY_MANIFEST_SHA256}", "unexpected base image"',
        'rows = json.loads(Path("/candidate/overlay-integrity.json").read_text()) + json.loads(Path("/candidate/inspection-integrity.json").read_text())',
        'for row in rows:',
        '    src = Path("/opt/qwen38-prod") / row["path"]',
        '    raw = src.read_bytes()',
        '    assert len(raw) == row["bytes"] and hashlib.sha256(raw).hexdigest() == row["sha256"], src',
        '    dst = Path(row["target"])',
        '    dst.parent.mkdir(parents=True, exist_ok=True)',
        '    if dst.is_symlink():',
        '        dst.unlink()',
        '    shutil.copyfile(src, dst)',
        '    os.chmod(dst, 0o644)',
        '    if dst.suffix == ".py":',
        '        compile(raw, str(dst), "exec")',
        'for d in ("/cache", "/results", "/candidate-model"):',
        '    os.makedirs(d, exist_ok=True)',
        '    os.chmod(d, 0o1777)',
        'print("baked", len(rows), "files")',
        'PY',
        'RUN /usr/bin/python3 -I -c "import importlib.metadata as m; assert any(e.name == \'nvidia_runtime_inspection\' for e in m.entry_points(group=\'vllm.endpoint_plugins\'))"',
    ]
    env_items = sorted(env.items())
    lines.append('ENV ' + ' \\\n    '.join(f'{k}={json.dumps(v)}' for k, v in env_items))
    lines += [
        'LABEL org.opencontainers.image.title="Qwen3.8-27B dense SM120 NVFP4 production (2026-09-23)" \\',
        '      org.opencontainers.image.source="https://github.com/wjxssb/qwen38-27b-dual-gpu-vllm" \\',
        '      org.opencontainers.image.licenses="Apache-2.0" \\',
        f'      ai.qwen38.base-image-id="{BASE_ID}" \\',
        f'      ai.qwen38.runtime-manifest-sha256="{manifest_sha}" \\',
        f'      ai.qwen38.model="nvidia/Qwen3.8-27B-NVFP4@{profiles["model_revision"]}" \\',
        '      ai.qwen38.profile="production-dense-recovery-20260923/graph-prefix" \\',
        '      ai.qwen38.validation="maintainer host production use; no public staged GPU gate for this image"',
        'WORKDIR /results',
        'ENTRYPOINT ["/usr/bin/python3", "-I", "/candidate/entry.py"]',
        'CMD ' + json.dumps(argv),
        '',
    ]
    (HERE / 'Dockerfile').write_text('\n'.join(lines))


if __name__ == '__main__':
    main()
