from common import *
import collections
baseline=NV/'cache-blessed/tree';fault=read(Q/'evidence/recovery-observer-r2-fault-1/receipt.json');runtime=NV/'candidate-v41-startup-observer-r2-20260923';actual=runtime/'runs'/fault['new_identity']['instance_id']/'cache'
rows=[]
for category,producer,key in [('cuda','CUDA driver module JIT','driver-generated kernel/architecture key'),('triton','Triton compiler','kernel source, specialization, options, target arch/compiler'),('torchinductor','PyTorch Inductor','graph/generated source and backend/version key'),('vllm','vLLM model registry','model module source hash and class; torch compilation mode=0'),('autotune','FlashInfer autotuner','runner/shape/dtype/tuning key, bound by sealed release inputs'),('frank-workspace','FlashInfer JIT/CUTLASS and local kernels','generated source, SM120, compiler/library ABI/build flags')]:
 b={str(p.relative_to(baseline/category)):sha(p) for p in (baseline/category).rglob('*') if p.is_file()};a={str(p.relative_to(actual/category)):sha(p) for p in (actual/category).rglob('*') if p.is_file()}
 changed=[k for k in b if k in a and b[k]!=a[k]];added=[k for k in a if k not in b]
 detail=[]
 for k in changed+added:
  p=actual/category/k;detail.append({'relative_path':k,'sha256':a[k],'mtime_epoch':p.stat().st_mtime,'present_before_ready':p.stat().st_mtime<=fault['timeline']['model_ready'],'size':p.stat().st_size})
 rows.append({'category':category,'path':str(actual/category),'baseline_path':str(baseline/category),'producer':producer,'consumer':'same pinned container release during initialization/inference','cache_key':key,'baseline_files':len(b),'baseline_bytes':sum((baseline/category/k).stat().st_size for k in b),'actual_files':len(a),'same_hash_count':sum(a.get(k)==v for k,v in b.items()),'changed':detail,'missing':[k for k in b if k not in a],'startup_hit_miss':'PERSISTED_FILES_VERIFIED; per-lookup hit/miss not globally instrumented. New/changed file timing separately recorded; existence is not proof every lookup hit.','safe_across_process_restart':'YES only same qualified release/input compatibility and source hashes','safe_across_release':'ONLY after native kernel/model/config/environment equality proof; no blanket reuse','safe_across_driver_change':'NOT_QUALIFIED; rebuild/requalify','safe_across_model_change':'NOT_QUALIFIED; rederive keys and rebuild/requalify'})
run=runtime/'runs'/fault['new_identity']['instance_id'];logs=(run/'logs/container.jsonl').read_text()
lines=[l for l in logs.splitlines() if any(s in l.lower() for s in ['autotun','compil','cache','kernel warmup','captur'])]
result={'state':'MEASURED_CACHE_CONTENTS_AND_LOGS','instance':fault['new_identity']['instance_id'],'manifest':sha(runtime/'MANIFEST.json'),'sources':{'baseline_bless':str(NV/'cache-blessed/bless.json'),'baseline_sha':sha(NV/'cache-blessed/bless.json'),'copy_provenance':str(runtime/'cache-blessed/cache-provenance.json'),'copy_provenance_sha':sha(runtime/'cache-blessed/cache-provenance.json')},'rows':rows,'startup_log_evidence':lines,'limits':['Cache-copy seeding uses sealed files, not prior poisoned CUDA/NCCL state. Graphs always recapture.','No silent claim of zero compilation: new Triton files exist and are retained for attribution.','vLLM persistent model-info cache is already implemented in the image; do not add a redundant cache based on a guess.','Hardware gate not shortened; cache preparation currently remains after gate.']}
save(Q/'recovery/RECOVERY-CACHE-INVENTORY.json',result)
print([(r['category'],r['baseline_files'],r['actual_files'],len(r['changed'])) for r in rows])
